export type Section = "Math" | "Reading & Writing";

export interface Question {
  id: string;
  section: Section;
  category: string;
  difficulty: "Easy" | "Medium" | "Hard";
  passage?: string;
  prompt: string;
  choices: string[];
  answer: number;
  explanation: string;
}

export const QUESTIONS: Question[] = [
  { id: "m1", section: "Math", category: "Algebra", difficulty: "Easy",
    prompt: "If 3x + 7 = 22, what is the value of x?",
    choices: ["3", "5", "7", "15"], answer: 1,
    explanation: "Subtract 7: 3x = 15. Divide by 3: x = 5." },
  { id: "m2", section: "Math", category: "Algebra", difficulty: "Easy",
    prompt: "If 5x − 3 = 2x + 9, what is the value of x?",
    choices: ["2", "3", "4", "6"], answer: 2,
    explanation: "5x − 2x = 9 + 3 → 3x = 12 → x = 4." },
  { id: "m3", section: "Math", category: "Algebra", difficulty: "Easy",
    prompt: "If 4(x + 2) = 28, what is x?",
    choices: ["3", "5", "7", "9"], answer: 1,
    explanation: "Divide by 4: x + 2 = 7, so x = 5." },
  { id: "m4", section: "Math", category: "Algebra", difficulty: "Medium",
    prompt: "If y/3 + 4 = 10, what is y?",
    choices: ["6", "14", "18", "42"], answer: 2,
    explanation: "y/3 = 6, so y = 18." },
  { id: "m5", section: "Math", category: "Algebra", difficulty: "Medium",
    prompt: "Which is the solution set of 3x − 7 > 11?",
    choices: ["x > 6", "x < 6", "x > 18", "x > 4"], answer: 0,
    explanation: "3x > 18 → x > 6." },
  { id: "m6", section: "Math", category: "Algebra", difficulty: "Medium",
    prompt: "A line has slope 2 and passes through (0, −3). What is its equation?",
    choices: ["y = 2x + 3", "y = 2x − 3", "y = −2x − 3", "y = 3x − 2"], answer: 1,
    explanation: "Slope-intercept form y = mx + b with m = 2 and b = −3 gives y = 2x − 3." },
  { id: "m7", section: "Math", category: "Algebra", difficulty: "Medium",
    prompt: "What is the slope of the line through (2, 5) and (6, 13)?",
    choices: ["1/2", "2", "3", "4"], answer: 1,
    explanation: "(13 − 5) / (6 − 2) = 8 / 4 = 2." },
  { id: "m8", section: "Math", category: "Algebra", difficulty: "Medium",
    prompt: "If 2x + 3y = 12 and x = 3, what is y?",
    choices: ["1", "2", "3", "4"], answer: 1,
    explanation: "6 + 3y = 12 → 3y = 6 → y = 2." },
  { id: "m9", section: "Math", category: "Algebra", difficulty: "Hard",
    prompt: "If x + y = 10 and x − y = 4, what is x?",
    choices: ["3", "5", "6", "7"], answer: 3,
    explanation: "Add the equations: 2x = 14 → x = 7." },
  { id: "m10", section: "Math", category: "Algebra", difficulty: "Easy",
    prompt: "If ½x − 4 = 0, what is x?",
    choices: ["2", "4", "8", "−8"], answer: 2,
    explanation: "½x = 4 → x = 8." },

  { id: "m11", section: "Math", category: "Advanced Math", difficulty: "Medium",
    prompt: "If f(x) = 2x² − 1, what is f(3)?",
    choices: ["11", "17", "18", "35"], answer: 1,
    explanation: "2(3²) − 1 = 2(9) − 1 = 18 − 1 = 17." },
  { id: "m12", section: "Math", category: "Advanced Math", difficulty: "Medium",
    prompt: "What are the solutions to x² = 49?",
    choices: ["7 only", "±7", "−7 only", "24.5"], answer: 1,
    explanation: "Both 7 and −7 square to 49, so x = ±7." },
  { id: "m13", section: "Math", category: "Advanced Math", difficulty: "Hard",
    prompt: "What are the roots of x² + 7x + 12 = 0?",
    choices: ["−3 and −4", "3 and 4", "−2 and −6", "2 and 6"], answer: 0,
    explanation: "Factor: (x + 3)(x + 4) = 0, so x = −3 or x = −4." },
  { id: "m14", section: "Math", category: "Advanced Math", difficulty: "Medium",
    prompt: "If 3ˣ = 81, what is x?",
    choices: ["3", "4", "5", "9"], answer: 1,
    explanation: "81 = 3⁴, so x = 4." },
  { id: "m15", section: "Math", category: "Advanced Math", difficulty: "Medium",
    prompt: "Simplify: x³ · x⁴",
    choices: ["x⁷", "x¹²", "x⁵", "x"], answer: 0,
    explanation: "When multiplying like bases, add exponents: 3 + 4 = 7." },
  { id: "m16", section: "Math", category: "Advanced Math", difficulty: "Hard",
    prompt: "Expand: (2x + 3)(x − 1)",
    choices: ["2x² + x − 3", "2x² − x − 3", "2x² + 5x − 3", "2x² + x + 3"], answer: 0,
    explanation: "2x² − 2x + 3x − 3 = 2x² + x − 3." },
  { id: "m17", section: "Math", category: "Advanced Math", difficulty: "Hard",
    prompt: "If √(x + 5) = 4, what is x?",
    choices: ["9", "11", "16", "21"], answer: 1,
    explanation: "Square both sides: x + 5 = 16, so x = 11." },

  { id: "m18", section: "Math", category: "Problem Solving", difficulty: "Easy",
    prompt: "A $40 shirt is discounted 25%. What is the sale price?",
    choices: ["$10", "$30", "$32", "$15"], answer: 1,
    explanation: "75% of 40 = 0.75 × 40 = $30." },
  { id: "m19", section: "Math", category: "Problem Solving", difficulty: "Easy",
    prompt: "What is 15% of 240?",
    choices: ["24", "36", "40", "360"], answer: 1,
    explanation: "0.15 × 240 = 36." },
  { id: "m20", section: "Math", category: "Problem Solving", difficulty: "Medium",
    prompt: "A number increased by 30% equals 78. What is the number?",
    choices: ["48", "54", "60", "108"], answer: 2,
    explanation: "1.3 × n = 78 → n = 78 / 1.3 = 60." },
  { id: "m21", section: "Math", category: "Problem Solving", difficulty: "Medium",
    prompt: "The ratio of girls to boys is 3 to 2. If there are 30 students, how many are boys?",
    choices: ["10", "12", "15", "18"], answer: 1,
    explanation: "3 + 2 = 5 parts; 30 / 5 = 6 per part; boys = 2 × 6 = 12." },
  { id: "m22", section: "Math", category: "Problem Solving", difficulty: "Medium",
    prompt: "A car travels 150 miles in 3 hours. At that rate, how far in 5 hours?",
    choices: ["200 mi", "250 mi", "300 mi", "450 mi"], answer: 1,
    explanation: "Rate = 50 mph; 50 × 5 = 250 miles." },
  { id: "m23", section: "Math", category: "Problem Solving", difficulty: "Medium",
    prompt: "If a recipe uses 2 cups of flour for 3 dozen cookies, how many cups for 9 dozen?",
    choices: ["3", "4", "6", "9"], answer: 2,
    explanation: "9 dozen is 3× the amount, so 3 × 2 = 6 cups." },
  { id: "m24", section: "Math", category: "Data Analysis", difficulty: "Medium",
    prompt: "The average of 6, 10, and x is 9. What is x?",
    choices: ["9", "11", "12", "13"], answer: 1,
    explanation: "Sum must be 27; 6 + 10 = 16, so x = 11." },
  { id: "m25", section: "Math", category: "Data Analysis", difficulty: "Medium",
    prompt: "A bag holds 3 red and 5 blue marbles. What is the probability of drawing red?",
    choices: ["3/5", "3/8", "5/8", "1/3"], answer: 1,
    explanation: "3 red out of 8 total = 3/8." },
  { id: "m26", section: "Math", category: "Data Analysis", difficulty: "Hard",
    prompt: "A function gives y = 5, 8, 11 for x = 1, 2, 3. What is y when x = 5?",
    choices: ["14", "15", "16", "17"], answer: 3,
    explanation: "y increases by 3 each step (y = 3x + 2); at x = 5, y = 17." },

  { id: "m27", section: "Math", category: "Geometry", difficulty: "Easy",
    prompt: "What is the area of a triangle with base 10 and height 6?",
    choices: ["16", "30", "32", "60"], answer: 1,
    explanation: "Area = ½ × base × height = ½ × 10 × 6 = 30." },
  { id: "m28", section: "Math", category: "Geometry", difficulty: "Easy",
    prompt: "A rectangle has length 12 and area 96. What is its width?",
    choices: ["6", "8", "9", "12"], answer: 1,
    explanation: "Width = area / length = 96 / 12 = 8." },
  { id: "m29", section: "Math", category: "Geometry", difficulty: "Medium",
    prompt: "A right triangle has legs 5 and 12. What is the hypotenuse?",
    choices: ["13", "15", "17", "60"], answer: 0,
    explanation: "√(5² + 12²) = √(25 + 144) = √169 = 13." },
  { id: "m30", section: "Math", category: "Geometry", difficulty: "Medium",
    prompt: "What is the area of a circle with radius 5? (Leave in terms of π.)",
    choices: ["10π", "25π", "5π", "50π"], answer: 1,
    explanation: "Area = πr² = π × 5² = 25π." },
  { id: "m31", section: "Math", category: "Geometry", difficulty: "Medium",
    prompt: "What is the volume of a cube with edge length 4?",
    choices: ["12", "16", "48", "64"], answer: 3,
    explanation: "Volume = side³ = 4³ = 64." },
  { id: "m32", section: "Math", category: "Geometry", difficulty: "Easy",
    prompt: "Two angles of a triangle are 50° and 60°. What is the third?",
    choices: ["60°", "70°", "80°", "90°"], answer: 1,
    explanation: "Angles sum to 180°: 180 − 50 − 60 = 70°." },
  { id: "m33", section: "Math", category: "Geometry", difficulty: "Hard",
    prompt: "Two triangles are similar. A side of 4 in the small one matches 10 in the large one. What matches a small side of 6?",
    choices: ["12", "15", "16", "24"], answer: 1,
    explanation: "Scale factor = 10/4 = 2.5; 6 × 2.5 = 15." },

  { id: "w1", section: "Reading & Writing", category: "Grammar", difficulty: "Easy",
    prompt: "The list of approved items ___ posted near the door.",
    choices: ["are", "is", "were", "have been"], answer: 1,
    explanation: "The subject is the singular \"list,\" not \"items,\" so use \"is.\"" },
  { id: "w2", section: "Reading & Writing", category: "Grammar", difficulty: "Medium",
    prompt: "The committee announced ___ decision on Friday.",
    choices: ["their", "its", "it's", "they're"], answer: 1,
    explanation: "\"Committee\" is a singular collective noun, so the possessive is \"its.\"" },
  { id: "w3", section: "Reading & Writing", category: "Grammar", difficulty: "Medium",
    prompt: "Each of the runners ___ a number on race day.",
    choices: ["have", "has", "were having", "are"], answer: 1,
    explanation: "\"Each\" is singular and takes the singular verb \"has.\"" },
  { id: "w4", section: "Reading & Writing", category: "Grammar", difficulty: "Easy",
    prompt: "Last summer, she ___ to Spain with her family.",
    choices: ["travels", "has traveled", "traveled", "will travel"], answer: 2,
    explanation: "\"Last summer\" signals a completed past action: simple past \"traveled.\"" },
  { id: "w5", section: "Reading & Writing", category: "Grammar", difficulty: "Hard",
    prompt: "By next June, I ___ here for ten years.",
    choices: ["work", "worked", "will have worked", "have worked"], answer: 2,
    explanation: "An action completed by a future point uses the future perfect: \"will have worked.\"" },
  { id: "w6", section: "Reading & Writing", category: "Grammar", difficulty: "Medium",
    prompt: "Which sentence is punctuated correctly?",
    choices: [
      "Before leaving she locked the door.",
      "Before leaving, she locked the door.",
      "Before, leaving she locked the door.",
      "Before leaving she, locked the door.",
    ], answer: 1,
    explanation: "An introductory phrase is followed by a comma before the main clause." },
  { id: "w7", section: "Reading & Writing", category: "Grammar", difficulty: "Hard",
    prompt: "Which sentence is punctuated correctly?",
    choices: [
      "My brother who lives in Texas, is visiting.",
      "My brother, who lives in Texas is visiting.",
      "My brother, who lives in Texas, is visiting.",
      "My brother who lives in Texas is visiting.",
    ], answer: 2,
    explanation: "A nonessential clause is set off by commas on both sides." },
  { id: "w8", section: "Reading & Writing", category: "Grammar", difficulty: "Medium",
    prompt: "Which correctly joins the two independent clauses?",
    choices: [
      "It rained all day, the game was canceled.",
      "It rained all day; the game was canceled.",
      "It rained all day the game was canceled.",
      "It rained all day so, the game was canceled.",
    ], answer: 1,
    explanation: "A semicolon correctly links two complete, related clauses. A comma alone is a splice." },
  { id: "w9", section: "Reading & Writing", category: "Grammar", difficulty: "Medium",
    prompt: "The ___ toys were scattered across the floor.",
    choices: ["childrens", "children's", "childrens'", "childs"], answer: 1,
    explanation: "\"Children\" is already plural, so the possessive adds 's: \"children's.\"" },
  { id: "w10", section: "Reading & Writing", category: "Grammar", difficulty: "Easy",
    prompt: "The dog wagged ___ tail happily.",
    choices: ["it's", "its", "its'", "it is"], answer: 1,
    explanation: "\"Its\" is the possessive; \"it's\" means \"it is.\"" },
  { id: "w11", section: "Reading & Writing", category: "Grammar", difficulty: "Medium",
    prompt: "Between you and ___, I think the plan is risky.",
    choices: ["I", "me", "myself", "mine"], answer: 1,
    explanation: "After the preposition \"between,\" use the object pronoun \"me.\"" },
  { id: "w12", section: "Reading & Writing", category: "Grammar", difficulty: "Hard",
    prompt: "___ did you give the book to?",
    choices: ["Who", "Whom", "Whose", "Who's"], answer: 1,
    explanation: "It's the object of \"to,\" so use \"whom\" (you gave it to him/whom)." },
  { id: "w13", section: "Reading & Writing", category: "Grammar", difficulty: "Hard",
    prompt: "Which sentence avoids a dangling modifier?",
    choices: [
      "Walking home, a fox appeared.",
      "Walking home, the fox was seen by me.",
      "Walking home, I saw a fox.",
      "Walking home a fox I saw.",
    ], answer: 2,
    explanation: "The one walking must follow the modifier — \"I\" was walking, so \"I saw a fox.\"" },
  { id: "w14", section: "Reading & Writing", category: "Grammar", difficulty: "Medium",
    prompt: "She likes hiking, swimming, and ___.",
    choices: ["to bike", "biking", "bikes", "she bikes"], answer: 1,
    explanation: "Parallel structure needs another -ing gerund: \"biking.\"" },
  { id: "w15", section: "Reading & Writing", category: "Grammar", difficulty: "Medium",
    prompt: "The job requires focus, patience, and ___.",
    choices: ["being creative", "to be creative", "creativity", "creatively"], answer: 2,
    explanation: "To match the nouns \"focus\" and \"patience,\" use the noun \"creativity.\"" },

  { id: "w16", section: "Reading & Writing", category: "Transitions", difficulty: "Medium",
    prompt: "The experiment failed twice. ___, the team refused to give up.",
    choices: ["Therefore", "Nevertheless", "For example", "In addition"], answer: 1,
    explanation: "There's a contrast (failure vs. not quitting), so \"Nevertheless\" fits." },
  { id: "w17", section: "Reading & Writing", category: "Transitions", difficulty: "Medium",
    prompt: "Sales rose all spring. ___, they fell sharply in winter.",
    choices: ["Moreover", "However", "As a result", "Similarly"], answer: 1,
    explanation: "The two facts contrast, so use \"However.\"" },
  { id: "w18", section: "Reading & Writing", category: "Transitions", difficulty: "Easy",
    prompt: "He saved for months. ___, he could finally afford the trip.",
    choices: ["Nonetheless", "As a result", "In contrast", "For instance"], answer: 1,
    explanation: "Saving caused him to afford it — a cause/effect, so \"As a result.\"" },
  { id: "w19", section: "Reading & Writing", category: "Transitions", difficulty: "Hard",
    prompt: "Many big cities struggle with traffic. ___, Tokyo keeps it moving with its train system.",
    choices: ["However", "For example", "Therefore", "Meanwhile"], answer: 0,
    explanation: "Tokyo is an exception to the struggle, a contrast, so \"However\" fits best." },
  { id: "w20", section: "Reading & Writing", category: "Concision", difficulty: "Medium",
    prompt: "Which version is clearest and most concise?",
    choices: [
      "We met together at twelve noon.",
      "We met at noon.",
      "We met at the time of noon.",
      "We had a meeting at noon time.",
    ], answer: 1,
    explanation: "\"At noon\" already means twelve midday; the rest is redundant." },

  { id: "w21", section: "Reading & Writing", category: "Vocabulary", difficulty: "Medium",
    passage: "The scientist's meticulous notes left out no detail, however small.",
    prompt: "As used here, \"meticulous\" most nearly means:",
    choices: ["careless", "careful", "quick", "secret"], answer: 1,
    explanation: "Leaving out no detail describes careful, precise work." },
  { id: "w22", section: "Reading & Writing", category: "Vocabulary", difficulty: "Medium",
    passage: "Her reply was brusque — almost rude — and the room went quiet.",
    prompt: "As used here, \"brusque\" most nearly means:",
    choices: ["gentle", "abrupt", "cheerful", "formal"], answer: 1,
    explanation: "Paired with \"almost rude,\" brusque means blunt or abrupt." },
  { id: "w23", section: "Reading & Writing", category: "Vocabulary", difficulty: "Hard",
    passage: "The novel's ambiguous ending left readers arguing about what really happened.",
    prompt: "As used here, \"ambiguous\" most nearly means:",
    choices: ["exciting", "unclear", "sad", "predictable"], answer: 1,
    explanation: "If readers can't agree what happened, the ending is open to interpretation — unclear." },
  { id: "w24", section: "Reading & Writing", category: "Reading", difficulty: "Medium",
    passage: "Bees pollinate a large share of the crops people eat, so a sharp decline in bee populations would threaten the food supply.",
    prompt: "Which best states the main idea?",
    choices: [
      "Bees are dangerous to most crops.",
      "Bees matter to our food supply.",
      "Crops do not depend on bees.",
      "Bee populations are growing fast.",
    ], answer: 1,
    explanation: "The sentence ties bees to crops and the food supply — they matter to it." },
  { id: "w25", section: "Reading & Writing", category: "Reading", difficulty: "Easy",
    passage: "Maria packed sunscreen, a beach towel, and her swimsuit before heading out the door.",
    prompt: "It can reasonably be inferred that Maria is:",
    choices: ["going swimming or to the beach", "going to school", "going to sleep", "afraid of the sun"], answer: 0,
    explanation: "Sunscreen, a beach towel, and a swimsuit all point to swimming or the beach." },
  { id: "w26", section: "Reading & Writing", category: "Reading", difficulty: "Hard",
    passage: "To make her case, the author cites three separate studies that each found regular exercise improves memory.",
    prompt: "The author most likely includes the studies in order to:",
    choices: ["entertain the reader", "support a claim with evidence", "tell a personal story", "criticize scientists"], answer: 1,
    explanation: "Citing studies provides evidence that backs up the author's claim." },
  { id: "w27", section: "Reading & Writing", category: "Reading", difficulty: "Medium",
    passage: "The autumn festival, held every October, features dishes from more than twenty countries.",
    prompt: "According to the passage, which is true of the festival?",
    choices: ["It is held weekly.", "It features food from over twenty countries.", "It happens in spring.", "It serves no food."], answer: 1,
    explanation: "The passage states it features dishes from more than twenty countries." },
  { id: "w28", section: "Reading & Writing", category: "Reading", difficulty: "Hard",
    passage: "A town council member claims the old bridge is no longer safe to use.",
    prompt: "Which finding would best support that claim?",
    choices: [
      "The bridge was built many years ago.",
      "Inspectors found deep cracks in its main supports.",
      "Many cars cross the bridge each day.",
      "The bridge is painted gray.",
    ], answer: 1,
    explanation: "Cracks in the main supports are direct evidence that it's unsafe; the others don't show danger." },
  { id: "w29", section: "Reading & Writing", category: "Reading", difficulty: "Medium",
    passage: "Finally — finally! — the package arrived, and I tore it open before the door even closed.",
    prompt: "The tone of the sentence is best described as:",
    choices: ["bored", "eager", "angry", "indifferent"], answer: 1,
    explanation: "The repetition of \"finally\" and tearing it open show eager excitement." },
  { id: "w30", section: "Reading & Writing", category: "Reading", difficulty: "Medium",
    passage: "Unlike Mara, who feels most alive in a busy city, Tom loves the quiet of the countryside.",
    prompt: "The passage indicates that Tom and Mara:",
    choices: ["both prefer cities", "prefer different settings", "live in the same town", "dislike each other"], answer: 1,
    explanation: "\"Unlike\" signals contrast: Mara likes the city, Tom likes the countryside." },
];
